// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? '';
// Try common env names: publishable key or anon key
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ??
  import.meta.env.VITE_SUPABASE_ANON_KEY ??
  '';

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // Don't throw here — frontend should still boot and we handle fallback in hooks,
  // but log clearly so devs can fix env on deploy.
  console.warn(
    '[Supabase] Missing configuration: VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY (or VITE_SUPABASE_ANON_KEY) not set. ' +
      'Database requests will fail unless these vars are provided.'
  );
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Export boolean flag so hooks can decide to fallback when client is not configured
export const supabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);